version: '3'

networks: 
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.3.0/24

volumes:
  pgdata:
    driver: local

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: 'no'
    ports: 
      - '8080:15672'
      - '5672:5672'
    networks: 
      - default